const style = {
  containerModal: {
    width: "100vw",
    height: "100vh",
    position: "fixed",
    top: 0,
    left: 0,
    zIndex: 11,
    background: "rgba(0,0,0,0.6)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  containerContent: {
    width: "70%",
    height: "70%",
    borderRadius: 4,
    background: "rgba(210, 210, 210, 1)",
    padding: "40px 50px",
    boxSizing: "border-box",
    display: "grid",
    gridTemplateColumns: "2fr 2fr",
  },
  containerContentFirstColumn: {
    width: "100%",
    height: "100%",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
  },
  containerContentTitleBox: {
    width: "100%",
    display: "flex",
    justifyContent: "start",
  },
  containerContentTitle: {
    fontSize: 28,
    fontWeight: 800,
    color: "rgba(80, 80, 80, 1)",
  },
  signatureBoxInfo: {
    width: "80%",
    height: "100%",
    display: "flex",
    alignItems: "start",
    flexDirection: "column",
    marginTop: 20,
    background: "rgba(235, 235, 235, 1)",
    borderRadius: 4,
    boxShadow: "4px 4px 6px rgba(0,0,0,0.4)",
    padding: "30px",
    fontFamily: "sans",
    gap: 5,
  },
  infoContentBox: {
    width: "100%",
    display: "flex",
    justifyContent: "start",
    gap: 5,
  },
  infoContentBoxTitle: {
    fontSize: 16,
    color: "rgba(20, 20, 20, 1)",
    fontWeight: 800,
    textDecoration: "underline",
  },
  infoContentBoxValue: {
    fontSize: 16,
    color: "rgba(80, 80, 80, 1)",
    fontWeight: 600,
  },
  assustaEle: {
    width: "100%",
    padding: "15px 20px",
    background: "rgba(200, 0, 0, 0.3)",
    display: "flex",
    justifyContent: "start",
    boxSizing: "border-box",
    textAlign: "start",
    marginTop: 10,
  },
  assustaEleBold: {
    fontWeight: 600,
    color: "rgba(0, 0, 0, 1)",
  },
  assustaEleNormal: {
    fontWeight: 500,
    color: "rgba(20, 20, 20, 1)",
  },
  priceBox: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    marginTop: 10,
  },
  priceBoxTitle: {
    fontSize: 22,
    fontWeight: 600,
    color: "black",
  },
  priceBoxValue: {
    fontSize: 22,
    fontWeight: 600,
    color: "rgba(0, 160, 0, 1)",
  },
  priceBoxBottom: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    marginTop: 10,
  },
  priceBoxTitleBottom: {
    fontSize: 18,
    fontWeight: 600,
    color: "black",
  },
  priceBoxValueBottom: {
    fontSize: 16,
    fontWeight: 600,
    color: "rgba(0, 200, 220, 1)",
  },
  containerContentSecondColumn: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 10
  },
  generatePixButton: {
    width: "100%",
    padding: "10px 10px",
    background: "rgba(100, 200, 0, 1)",
    border: "2px solid black",
    borderRadius: 4,
    cursor: "pointer",
    boxShadow: "3px 3px 4px rgba(0,0,0,0.4)",
    fontSize: 18,
    fontWeight: 600,
    outline: "none",
    color: "rgba(80, 80, 80, 1)"
  },
  payAfterButton: {
    width: "100%",
    padding: "10px 10px",
    background: "rgba(0, 150, 220, 1)",
    border: "2px solid black",
    borderRadius: 4,
    cursor: "pointer",
    boxShadow: "3px 3px 4px rgba(0,0,0,0.4)",
    fontSize: 18,
    fontWeight: 600,
    outline: "none",
    color: "rgba(0, 0, 0, 1)"
  }
};

export default style;
