const style = {
  container: {
    width: "100vw",
    height: "100vh",
    position: "fixed",
    top: 0,
    left: 0,
    boxSizing: "border-box",
    background: "rgba(0,0,0,0.6)",
    zIndex: 10,
  },
  containerContent: {
    width: "100%",
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    width: 400,
    boxSizing: "border-box",
    padding: 30,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    position: "relative",
    background: "rgba(220, 220, 220, 1)",
    borderRadius: 8,
  },
  close: {
    fontSize: 18,
    fontWeight: 800,
    color: "rgba(80, 80, 80, 1)",
    cursor: "pointer",
    position: "absolute",
    top: 20,
    left: 30
  },
  modalTitle: {
    fontSize: 26,
    color: "rgba(80, 80, 80, 1)",
    fontWeight: 800,
  },
  inputBox: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    marginTop: 20,
  },
  textBoxTitle: {
    fontSize: 16,
    width: "100%",
    textAlign: "start",
    color: "rgba(50, 50, 50, 1)",
    fontWeight: 500
  },
  input: {
    width: "100%",
    height: 35,
    border: 0,
    boxSizing: "border-box",
    boxShadow: "3px 3px 1px rgba(0,0,0,0.2)",
    outline: "none",
    padding: 0,
    paddingLeft: 20,
    fontSize: 18,
  },
  messageBox1: {
    width: "100%",
    height: 40,
    border: 0,
    boxShadow: "3px 3px 1px rgba(0,0,0,0.2)",
    outline: "none",
    padding: 0,
    paddingLeft: 20,
    boxSizing: "border-box",
    fontSize: 18,
  },
  messageBox2: {
    width: "100%",
    height: 100,
    border: 0,
    boxShadow: "3px 3px 1px rgba(0,0,0,0.2)",
    outline: "none",
    paddingLeft: 5,
    boxSizing: "border-box",
    fontSize: 18,
  },
  sendMessage: {
    marginTop: 10,
    width: "100%",
    height: 35,
    border: 0,
    boxSizing: "border-box",
    padding: 0,
    background: "rgba(100, 200, 0, 1)",
    color: "rgba(80, 80, 80, 1)",
    fontSize: 18,
    fontWeight: 500,
    cursor: "pointer",
  },
};

export default style;
