const style = {
  sidebarContainer: {
    width: "100px",
    height: "95vh",
    background: "#9CEC5B",
    position: "fixed",
    top: "50%",
    left: "2vh",
    transform: "translateY(-50%) translateX(0)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    borderRadius: 4,
    boxShadow: "3px 4px 10px rgba(0,0,0,0.4)",
    zIndex: 9,
    transition: "transform 0.5s ease-in-out, opacity 0.5s ease-in-out", 
  },
  sidebarContainerClosed: {
    transform: "translateY(-50%) translateX(-100%)", // Move para esquerda (fora da tela)
    opacity: 0,
    width: "100px",
    height: "95vh",
    background: "#9CEC5B",
    position: "fixed",
    top: "50%",
    left: "2vh",
    transform: "translateY(-50%) translateX(0)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    borderRadius: 4,
    boxShadow: "3px 4px 10px rgba(0,0,0,0.4)",
    zIndex: 9,
    transition: "transform 0.5s ease-in-out, opacity 0.5s ease-in-out", 
  },
  sidebarContent: {
    width: "100%",
    height: "100%",
    display: "grid",
    gridTemplateRows: "4fr 10fr",
    padding: 20,
    boxSizing: "border-box",
    position: "relative",
  },
  closeIconBox: {
    position: "absolute",
    top: 30,
    left: "50%",
    transform: "translateX(-50%)",
    width: 30,
    height: 30,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    cursor: "pointer",
  },
  closeIcon: {
    width: "100%",
  },
  header: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  logoBox: {
    width: 200,
    height: 200,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  logoImage: {
    width: "100%",
  },
  agenteTitleBox: {
    width: "auto",  // Remove a largura fixa
    height: "100%", 
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    margin: "0 10px",
    marginTop: 100,
  },
  agenteTitle: {
    fontSize: "1.4rem",
    textShadow: "2px 2px 1px rgba(0,0,0,0.5)",
    color: "rgba(255, 255, 255, 1)",
    fontWeight: 600,
    writingMode: "vertical-rl", // Texto vertical (right-to-left)
    textOrientation: "mixed",  // Mantém a orientação dos caracteres
    transform: "rotate(180deg)", // Opcional: inverte a direção (se necessário)
    letterSpacing: "2px", // Melhora a legibilidade
  },
  menu: {
    width: "100%",
    height: "100%",
    display: "grid",
    gridTemplateRows: "80% 20%",
  },
  menuContent: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 20,
  },
  menuItems: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  menuItemsCenter: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  menuItem: {
    // width: "100%",
    height: "2.8rem",
    display: "grid",
    gridTemplateColumns: "35px auto",
    boxSizing: "border-box",
    cursor: "pointer",
    // transition: ".3s",
  },
  menuItemIconBox: {
    width: "100%",
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItem: "center",
    position: "relative"
  },
  menuItemIcon: {
    width: "100%",
  },
  menuItemTextBox: {
    // width: 230,
    padding: "0px 30px",
    // display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    top: 0,
    left: 80,
    borderRadius: "0px 30px 30px 0px",
    height: "100%",
    background: "rgba(156, 236, 91, 1)",
    overflow: "hidden"
  },
  menuItemText: {
    width: "100%",
    color: "rgba(80, 80, 80, 1)",
    fontWeight: 600,
    fontSize: 22,
  },
  userButtonBox: {
    width: "100%",
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  userButton: {
    width: "100%",
    height: "75px",
    // background: "#50C5B7",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    borderRadius: 4,
    cursor: "pointer",
    transition: ".3s",
  },
  userImageBox: {
    width: 50,
    height: 50,
    borderRadius: "50%",
    border: "3px solid #FFFFFF",
    boxSizing: "border-box",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  userImage: {
    width: "140%",
  },
  username: {
    fontSize: 28,
    color: "#FFFFFF",
    textShadow: "2px 2px 1px rgba(0,0,0,0.4)",
    fontWeight: 600,
  },
};

export default style;
