const style = {
  container: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    padding: "80px 50px",
    alignItems: "start",
    boxSizing: "border-box",
    position: "relative",
  },
  title: {
    fontSize: 38,
    fontWeight: 800,
    color: "rgba(80, 80, 80, 1)",
  },
  header: {
    marginTop: 10,
    width: "100%",
    display: "grid",
    height: 120,
    gridTemplateColumns: "3fr 2fr",
    alignItems: "center",
    justifyContent: "center",
    gap: 10
  },
  headerBox: {
    width: "100%",
    height: "100%",
    padding: 30,
    background: "rgba(210, 210, 210, 1)",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
    textAlign: "start",
    boxShadow: "3px 3px 4px rgba(0,0,0,0.4)",
    borderRadius: 4
  },
  headerText: {
    fontSize: 16,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
    boxSizing: "border-box",
  },
  headerButtonsBox: {
    width: "100%",
    height: "100%",
    boxSizing: "border-box",
    display: "grid",
    gridTemplateColumns: "2fr 2fr",
    gridTemplateRows: "2fr 2fr",
    gap: 10
  },
  headerButton: {
    width: "100%",
    height: "100%",
    borderRadius: 4,
    boxShadow: "3px 3px 4px rgba(0,0,0,0.4)",
    cursor: "pointer",
    fontSize: 18,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
    border: 0,
    boxSizing: "border-box"
  },
  searchArea: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "60% 25% 15%",
    overflow: "hidden",
    padding: "10px 20px",
    marginTop: 20,
    boxSizing: "border-box",
    alignItems: "end",
    justifyContent: "center",
    gap: 10,
  },
  searchBarBoxContainer: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
  },
  searchBarBoxContainerTitle: {
    fontSize: 24,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
  },
  searchBarBox: {
    width: "100%",
    height: 40,
    boxSizing: "border-box",
    display: "grid",
    gridTemplateColumns: "100%",
    gap: 10,
  },
  searchBarInput: {
    width: "100%",
    border: 0,
    boxSizing: "border-box",
    padding: 0,
    paddingLeft: 20,
    borderRadius: 4,
    background: "white",
    boxShadow: "4px 4px 3px rgba(0,0,0,0.2)",
    fontSize: 16,
    outline: "none",
  },
  searchButton: {
    width: "100%",
    height: 40,
    borderRadius: 4,
    cursor: "pointer",
    transition: ".3s",
    border: 0,
    background: "rgba(210, 210, 210, 1)",
    fontSize: 18,
    fontWeight: 600,
    boxSizing: "border-box",
    boxShadow: "4px 4px 3px rgba(0,0,0,0.2)",
  },
  filters: {
    width: "100%",
    height: "100%",
    display: "grid",
    gridTemplateColumns: "100%",
    boxSizing: "border-box",
    gap: 10,
  },
  filterBox: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
    justifyContent: "end",
  },
  filterBoxName: {
    fontSize: 16,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
  },
  filter: {
    display: "flex",
    gap: 10,
    height: 40,
    boxSizing: "border-box",
    width: "100%",
  },
  filterInput: {
    width: "100%",
    border: 0,
    boxSizing: "border-box",
    padding: 0,
    paddingLeft: 20,
    borderRadius: 4,
    background: "white",
    boxShadow: "4px 4px 3px rgba(0,0,0,0.2)",
    fontSize: 16,
    outline: "none",
  },
  filterSelect: {
    width: "100%",
    border: 0,
    boxSizing: "border-box",
    padding: 0,
    borderRadius: 4,
    background: "white",
    boxShadow: "4px 4px 3px rgba(0,0,0,0.2)",
    fontSize: 16,
    outline: "none",
  },
  filterButton: {
    width: "100%",
    border: 0,
    boxSizing: "border-box",
    padding: 0,
    borderRadius: 4,
    background: "rgba(0, 210, 100, 1)",
    boxShadow: "4px 4px 3px rgba(0,0,0,0.2)",
    fontSize: 16,
    outline: "none",
    cursor: "pointer",
  },
  tableContainer: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
    marginTop: 20,
  },
  tableTitle: {
    fontSize: 24,
    color: "rgba(80, 80, 80, 1)",
    fontWeight: 600,
  },
  table: {
    width: "100%",
    display: "grid",
    background: "rgba(255, 255, 255, 1)",
    gridTemplateRows: "40px auto",
    boxSizing: "border-box",
    borderRadius: "8px",
    overflow: "hidden",
    boxShadow: "0 2px 10px rgba(0,0,0,0.1)",
    border: "1px solid rgba(240, 240, 240, 1)",
  },

  tableHeader: {
    width: "100%",
    height: "100%",
    display: "grid",
    gridTemplateColumns: "4fr 4fr 2fr",
    background: "rgba(245, 245, 245, 1)",
    borderBottom: "1px solid rgba(230, 230, 230, 1)",
  },

  tableHeaderCell: {
    width: "100%",
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    boxSizing: "border-box",
    fontWeight: 600,
    fontSize: "14px",
    color: "rgba(80, 80, 80, 1)",
    textTransform: "uppercase",
    background: "red",
    letterSpacing: "0.5px",
  },
  tableHeaderCell1: {
    width: "100%",
    height: 35,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    boxSizing: "border-box",
    fontWeight: 600,
    fontSize: "14px",
    color: "rgba(80, 80, 80, 1)",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },

  tableBody: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "30px auto"
  },

  tableRow: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "4fr 4fr 2fr",
    alignItems: "center",
    padding: "10px 16px",
    boxSizing: "border-box",
    borderBottom: "1px solid rgba(240, 240, 240, 1)",
    transition: "background 0.2s ease",
    "&:hover": {
      background: "rgba(245, 245, 245, 1)",
    },
    "&:last-child": {
      borderBottom: "none",
    },
  },
  rollCell: {
    width: "100%",
    background: "red",
    display: "flex",
    justifyContent: "center"
  },

  tableCell: {
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    padding: "0 5px",
    boxSizing: "border-box",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },

  tableCellText: {
    fontSize: "14px",
    color: "rgba(100, 100, 100, 1)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  bottom: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "2fr 2fr 2fr",
  },
  paginationContainer: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    gap: 10,
    marginTop: 40,
  },
  paginationButton: {
    width: 120,
    height: 30,
    borderRadius: 4,
    background: "rgba(210, 210, 210, 1)",
    padding: 0,
    boxSizing: "border-box",
    border: 0,
    cursor: "pointer",
    fontSize: 16,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
  },
  actualPageBox: {
    height: 30,
    width: 200,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  actualPageText: {
    fontSize: 18,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
  },
  itemsPerPageContainer: {
    display: "flex",
    alignItems: "end",
    justifyContent: "end",
    gap: 10,
  },
  itemsPerPageText: {
    fontSize: 18,
    fontWeight: 500,
    color: "rgba(80, 80, 80, 1)",
  },
  itemsPerPageInput: {
    // width: 60,
    height: 30,
    outline: 0,
    border: 0,
    boxSizing: "border-box",
    padding: 5,
    textAlign: "center",
    fontSize: 16,
    fontWeight: 600,
    borderRadius: 4,
    background: "rgba(210, 210, 210, 1)",
  },
};

export default style;
