const style = {
  sidebarContainer: {
    width: "20vw",
    height: "95vh",
    background: "#0f4c5c",
    position: "fixed",
    top: "50%",
    left: "2vh",
    transform: "translateY(-50%) translateX(0)",
    display: "grid",
    gridTemplateRows: "30% 60% 10%",
    borderRadius: 4,
    boxShadow: "3px 4px 10px rgba(0,0,0,0.4)",
    zIndex: 9,
    overflow: "hidden",
    transition: "transform 0.5s ease-in-out, opacity 0.5s ease-in-out", // Transições específicas
  },
  sidebarContainerClosed: {
    transform: "translateY(-50%) translateX(-100%)", // Move para esquerda (fora da tela)
    opacity: 0,
    width: "20vw",
    height: "95vh",
    background: "#0f4c5c",
    position: "fixed",
    overflow: "hidden",
    top: "50%",
    left: "2vh",
    display: "grid",
    gridTemplateRows: "30% 60% 10%",
    borderRadius: 4,
    zIndex: 9,
    transition: "transform 0.5s ease-in-out, opacity 0.5s ease-in-out",
  },
  closeIconBox: {
    position: "absolute",
    top: 20,
    left: 20,
    width: 30,
    height: 30,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    cursor: "pointer",
  },
  closeIcon: {
    width: "100%",
  },
  companyLogo: {
    width: "100%",
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    boxSizing: "border-box",
    padding: 30,
  },
  companyLogoImage: {
    width: "80%",
  },
  routesBox: {
    width: "100%",
    height: "100%",
    display: "grid",
    gridTemplateRows: "2fr 2fr 2fr 2fr 2fr 2fr 2fr 2fr 2fr",
  },
  routeBox: {
    width: "100%",
    height: "100%",
    display: "grid",
    gridTemplateColumns: "80% 20%",
    padding: "0 20px",
    boxSizing: "border-box",
    cursor: "pointer",
    transition: ".3s",
  },
  routeTitle: {
    fontSize: 22,
    width: "100%",
    height: "100%",
    display: "flex",
    justifyContent: "start",
    alignItems: "center",
    fontWeight: 800,
    color: "rgba(210, 210, 210, 1)",
    padding: 0,
  },
  routeArrowBox: {
    width: "100%",
    height: "100%",
    display: "flex",
    justifyContent: "end",
    alignItems: "center",
  },
  routeArrow: {
    width: 32,
    transform: "scaleX(-1)",
  },
  bottom: {
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "end",
  },
  logoutButton: {
    width: "100%",
    height: "80%",
    border: 0,
    boxSizing: "border-box",
    outline: "none",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: 28,
    background: "rgba(140, 20, 0, 1)",
    color: "rgba(210, 210, 210, 1)"
  },
};

export default style;
