const style = {
  container: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    padding: "80px 50px",
    alignItems: "start",
    boxSizing: "border-box",
    position: "relative",
  },
  createNewShot: {
    width: 60,
    height: 60,
    borderRadius: "50%",
    boxSizing: "border-box",
    boxShadow: "4px 4px 4px rgba(0,0,0,0.4)",
    // background: "rgba(0, 200, 220, 1)",
    fontSize: 48,
    fontWeight: 800,
    color: "rgba(80, 80, 80, 1)",
    position: "absolute",
    bottom: 40,
    right: 30,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // padding: 30,
    textAlign: "center",
    transition: ".3s",
    cursor: "pointer",
  },
  createNewShotIcon: {
    width: "100%",
    borderRadius: "50%",
  },
  title: {
    fontSize: 38,
    fontWeight: 800,
    color: "rgba(80, 80, 80, 1)",
  },
  disparosHeaderContainer: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "2fr 2fr",
    gap: 10,
    height: 150,
  },
  disparosHeader: {
    width: "100%",
    padding: "10px 30px",
    display: "flex",
    height: "100%",
    justifyContent: "center",
    alignItems: "start",
    background: "rgba(210, 210, 210, 1)",
    boxSizing: "border-box",
    flexDirection: "column",
  },
  disparosHeaderInfoPart: {
    width: "100%",
    height: "100%",
    // background: "rgba(210, 210, 210, 1)",
    display: "grid",
    gridTemplateColumns: "2fr 2fr",
    gridTemplateRows: "2fr 2fr",
    gap: 10,
  },
  whiteViewInfo: {
    width: "100%",
    height: "100%",
    background: "white",
    borderRadius: 4,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    position: "relative"
  },
  obterDisparosButton: {
    fontSize: 14,
    fontWeight: 500,
    color: "rgba(0, 50, 255, 0.5)",
    position: "absolute",
    bottom: 5,
    right: 5,
    textDecoration: "underline",
    cursor: "pointer"
  },
  whiteViewInfoTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)"
  },
  whiteViewInfoValue: {
    fontSize: 16,
    fontWeight: 600,
    color: "rgba(80, 140, 140, 1)"
  },
  disparosHeaderText: {
    textAlign: "start",
    color: "rgba(80, 80, 80, 1)",
    fontWeight: 500,
  },
  disparosPart: {
    width: "100%",
    marginTop: 20,
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
  },
  disparosPartTitle: {
    fontSize: 26,
    fontWeight: 800,
    color: "rgba(80, 80, 80, 1)",
  },
  searchArea: {
    display: "grid",
    gridTemplateColumns: "4fr 1fr 1fr 2fr 2fr 1fr",
    gap: 10,
    marginTop: 20,
    width: "100%",
  },
  searchItem: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "start",
    flexDirection: "column",
  },
  searchItemTitle: {
    fontSize: 18,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
  },
  searchInput: {
    width: "100%",
    height: 35,
    boxSizing: "border-box",
    outline: "none",
    padding: 0,
    paddingLeft: 20,
    fontSize: 16,
    border: 0,
    borderRadius: 4,
    boxShadow: "3px 3px 4px rgba(0,0,0,0.2)",
  },
  selectTagsButton: {
    width: "100%",
    height: 35,
    boxSizing: "border-box",
    outline: "none",
    padding: 0,
    fontSize: 16,
    border: 0,
    fontWeight: 600,
    borderRadius: 4,
    background: "rgba(100, 200, 0, 1)",
    boxShadow: "3px 3px 4px rgba(0,0,0,0.2)",
    color: "rgba(80, 80, 80, 1)",
  },
  table: {
    width: "100%",
    display: "grid",
    gridTemplateRows: "40px 300px",
    marginTop: 20,
  },
  tableRowHeader: {
    width: "100%",
    background: "rgba(200, 200, 200, 1)",
    height: "100%",
    display: "grid",
    gridTemplateColumns: "3fr 3fr 2fr 2fr 2fr",
  },
  tableHeaderCell: {
    width: "100%",
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontSize: 18,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
  },
  tableBody: {
    width: "100%",
    height: "100%",
    display: "grid",
    gridTemplateRows: "auto",
  },
  tableRowBody: {
    width: "100%",
    background: "rgba(230, 230, 230, 1)",
    height: 40,
    display: "grid",
    gridTemplateColumns: "3fr 3fr 2fr 2fr 2fr",
  },
  //modal novo disparo
  containerSupremoModal: {
    width: "100vw",
    height: "100vh",
    position: "fixed",
    top: 0,
    left: 0,
    zIndex: 10,
    boxSizing: "border-box",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    background: "rgba(0,0,0,0.4)",
  },
  containerModal: {
    width: "90%",
    maxHeight: "90%",
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
    borderRadius: 4,
    boxSizing: "border-box",
    padding: "50px 80px 30px 80px",
    background: "rgba(210, 210, 210, 1)",
    position: "relative",
  },
  closeBtn: {
    position: "absolute",
    top: 20,
    left: 25,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
    transition: ".3s",
    fontSize: 28,
    cursor: "pointer",
  },
  modalTitle: {
    fontSize: 32,
    color: "rgba(80, 80, 80, 1)",
    fontWeight: 600,
  },
  principalConfiguration: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "2fr 2fr",
    height: 190,
    gap: 10,
    marginTop: 10,
  },
  principalConfigurationFirst: {
    width: "100%",
    display: "grid",
    height: "100%",
    gridTemplateRows: "40px 120px",
    gap: 10,
  },
  inputConfig: {
    width: "100%",
    height: "100%",
    border: 0,
    boxShadow: "3px 3px 3px rgba(0,0,0,0.2)",
    outline: "none",
    fontSize: 18,
    padding: 0,
    paddingLeft: 20,
    boxSizing: "border-box",
  },
  textareaConfig: {
    width: "100%",
    height: "100%",
    border: 0,
    boxShadow: "3px 3px 3px rgba(0,0,0,0.2)",
    outline: "none",
    fontSize: 18,
    padding: "10px 20px",
    boxSizing: "border-box",
  },
  principalConfigurationSecond: {
    width: "100%",
    height: "100%",
    display: "grid",
    gridTemplateRows: "40px 120px",
    gap: 10,
  },
  dateConfigBox: {
    width: "100%",
    height: "100%",
    display: "grid",
    gridTemplateColumns: "2fr 2fr",
    gap: 10,
  },
  inputDateConfigBox: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
    position: "relative",
  },
  inputDateConfigBoxTitle: {
    fontSize: 16,
    fontWeight: 500,
    color: "rgba(80, 80, 80, 1)",
    position: "absolute",
    top: -20,
    left: 0,
  },
  inputDateConfigBoxInput: {
    width: "100%",
    height: 40,
    border: 0,
    boxShadow: "3px 3px 3px rgba(0,0,0,0.2)",
    outline: "none",
    fontSize: 18,
    padding: 0,
    paddingLeft: 20,
    boxSizing: "border-box",
  },
  tagButtonContainer: {
    width: "100%",
    height: "100%",
    display: "grid",
    gridTemplateColumns: "2fr 2fr",
    gap: 10,
  },
  filterConfigs: {
    width: "100%",
    height: "100%",
    display: "grid",
    gridTemplateRows: "2fr 2fr",
    gap: 10,
  },
  shotsQttBox: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
  },
  shotsQttText: {
    fontSize: 16,
    fontWeight: 500,
    color: "rgba(80, 80, 80, 1)",
  },
  shotsQttInput: {
    fontSize: 16,
    boxSizing: "border-box",
    width: "100%",
    height: 35,
    outline: "none",
    padding: 0,
    paddingLeft: 20,
    border: 0,
    boxShadow: "3px 3px 3px rgba(0,0,0,0.2)",
  },
  tagButton: {
    width: "100%",
    height: "100%",
    borderRadius: 4,
    border: 0,
    boxSizing: "border-box",
    fontSize: 22,
    background: "rgba(100, 220, 0, 1)",
    color: "rgba(80, 80, 80, 1)",
    cursor: "pointer",
    transition: ".3s",
    boxShadow: "3px 3px 3px rgba(0,0,0,0.2)",
    fontWeight: 600,
  },
  statusFilter: {
    width: "100%",
    height: "100%",
    outline: "none",
    border: 0,
    boxSizing: "border-box",
    padding: 0,
    textAlign: "center",
    fontSize: 22,
    border: 0,
    boxShadow: "3px 3px 3px rgba(0,0,0,0.2)",
    color: "rgba(80, 80, 80, 1)",
    fontWeight: 600,
  },
  secondConfiguration: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  isForNewContactsBox: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  isForNewContactsBoxTitle: {
    fontSize: 18,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
  },
  isForNewContactsBoxInputs: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 20,
  },
  observacao: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "20px 0",
    fontSize: 16,
    color: "rgba(200, 80, 80, 1)",
    fontWeight: 600,
  },
  radioBox: {
    display: "flex",
    gap: 5,
  },
  radioBoxText: {
    fontSize: 20,
    fontWeight: 500,
    color: "rgba(80, 80, 80, 1)",
  },
  radioInput: {
    width: 20,
    height: 20,
  },
  selectNewNumbersBox: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    marginTop: 10,
  },
  selectNewNumbersButton: {
    height: 35,
    boxSizing: "border-box",
    padding: 0,
    padding: "0 20px",
    fontSize: 16,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
    background: "rgba(160, 160, 160, 1)",
    border: 0,
    borderRadius: 4,
    cursor: "pointer",
  },
  selectMessageModelBox: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
    marginTop: 20,
  },
  selectMessageModelBoxTitle: {
    fontSize: 18,
    color: "rgba(80, 80, 80, 1)",
    fontWeight: 600,
  },
  typeMessageBox: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
    marginTop: 20,
  },
  typeMessageBoxTitle: {
    fontSize: 18,
    color: "rgba(80, 80, 80, 1)",
    fontWeight: 600,
  },
  typeMessageBoxInput: {
    width: "100%",
    height: 200,
    fontWeight: 500,
    fontSize: 16,
    padding: "10px 20px",
    boxSizing: "border-box",
    outline: "none",
    border: 0,
    boxShadow: "3px 3px 3px rgba(0,0,0,0.4)",
  },
  createButton: {
    width: "100%",
    height: 40,
    border: 0,
    background: "rgba(100, 220, 0, 1)",
    color: "rgba(80, 80, 80, 1)",
    boxSizing: "border-box",
    fontSize: 18,
    marginTop: 10,
    borderRadius: 4,
    cursor: "pointer",
    transition: ".3s",
  },
  shotTypeContainer: {
    display: "flex",
    gap: 10,
    marginTop: 10,
  },
  shotTypeContainerButton: {
    width: 200,
    height: 35,
    borderRadius: 4,
    boxSizing: "border-box",
    fontSize: 16,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
    border: 0,
    boxShadow: "3px 3px 2px rgba(0,0,0,0.1)",
    cursor: "pointer",
  },
  //fim modal novo disparo
  //começo modal novo disparo remarketing
  containerSupremoModal2: {
    width: "100vw",
    height: "100vh",
    position: "fixed",
    top: 0,
    left: 0,
    zIndex: 10,
    boxSizing: "border-box",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    background: "rgba(0,0,0,0.4)",
  },
  containerModal2: {
    width: "90%",
    maxHeight: "90%",
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
    borderRadius: 4,
    boxSizing: "border-box",
    padding: "50px 80px 30px 80px",
    background: "rgba(210, 210, 210, 1)",
    position: "relative",
  },
  closeBtn2: {
    position: "absolute",
    top: 20,
    left: 25,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
    transition: ".3s",
    fontSize: 28,
    cursor: "pointer",
  },
  modalTitle2: {
    fontSize: 32,
    color: "rgba(80, 80, 80, 1)",
    fontWeight: 600,
  },
  principalConfiguration2: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "2fr 2fr",
    height: 190,
    gap: 10,
    marginTop: 10,
  },
  principalConfigurationFirst2: {
    width: "100%",
    display: "grid",
    height: "100%",
    gridTemplateRows: "40px 120px",
    gap: 10,
  },
  inputConfig2: {
    width: "100%",
    height: "100%",
    border: 0,
    boxShadow: "3px 3px 3px rgba(0,0,0,0.2)",
    outline: "none",
    fontSize: 18,
    padding: 0,
    paddingLeft: 20,
    boxSizing: "border-box",
  },
  textareaConfig2: {
    width: "100%",
    height: "100%",
    border: 0,
    boxShadow: "3px 3px 3px rgba(0,0,0,0.2)",
    outline: "none",
    fontSize: 18,
    padding: "10px 20px",
    boxSizing: "border-box",
  },
  principalConfigurationSecond2: {
    width: "100%",
    height: "100%",
    display: "grid",
    gridTemplateRows: "170px",
    gap: 10,
  },
  dateConfigBox2: {
    width: "100%",
    height: "100%",
    display: "grid",
    gridTemplateColumns: "2fr 2fr",
    gap: 10,
  },
  inputDateConfigBox2: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
    position: "relative",
  },
  inputDateConfigBoxTitle2: {
    fontSize: 16,
    fontWeight: 500,
    color: "rgba(80, 80, 80, 1)",
    position: "absolute",
    top: -20,
    left: 0,
  },
  inputDateConfigBoxInput2: {
    width: "100%",
    height: 40,
    border: 0,
    boxShadow: "3px 3px 3px rgba(0,0,0,0.2)",
    outline: "none",
    fontSize: 18,
    padding: 0,
    paddingLeft: 20,
    boxSizing: "border-box",
  },
  tagButtonContainer2: {
    width: "100%",
    height: "100%",
    display: "grid",
    gridTemplateColumns: "2fr 2fr",
    gap: 10,
  },
  filterConfigs2: {
    width: "100%",
    height: "100%",
    display: "grid",
    gridTemplateRows: "2fr 2fr",
    gap: 10,
  },
  shotsQttBox2: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
  },
  shotsQttText2: {
    fontSize: 16,
    fontWeight: 500,
    color: "rgba(80, 80, 80, 1)",
  },
  shotsQttInput2: {
    fontSize: 16,
    boxSizing: "border-box",
    width: "100%",
    height: 35,
    outline: "none",
    padding: 0,
    paddingLeft: 20,
    border: 0,
    boxShadow: "3px 3px 3px rgba(0,0,0,0.2)",
  },
  tagButton2: {
    width: "100%",
    height: "100%",
    borderRadius: 4,
    border: 0,
    boxSizing: "border-box",
    fontSize: 22,
    background: "rgba(100, 220, 0, 1)",
    color: "rgba(80, 80, 80, 1)",
    cursor: "pointer",
    transition: ".3s",
    boxShadow: "3px 3px 3px rgba(0,0,0,0.2)",
    fontWeight: 600,
  },
  statusFilter2: {
    width: "100%",
    height: 35,
    outline: "none",
    border: 0,
    boxSizing: "border-box",
    padding: 0,
    textAlign: "center",
    fontSize: 22,
    border: 0,
    boxShadow: "3px 3px 3px rgba(0,0,0,0.2)",
    color: "rgba(80, 80, 80, 1)",
    fontWeight: 600,
  },
  secondConfiguration2: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  isForNewContactsBox2: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  isForNewContactsBoxTitle2: {
    fontSize: 18,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
  },
  isForNewContactsBoxInputs2: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 20,
  },
  observacao2: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "20px 0",
    fontSize: 16,
    color: "rgba(200, 80, 80, 1)",
    fontWeight: 600,
  },
  radioBox2: {
    display: "flex",
    gap: 5,
  },
  radioBoxText2: {
    fontSize: 20,
    fontWeight: 500,
    color: "rgba(80, 80, 80, 1)",
  },
  radioInput2: {
    width: 20,
    height: 20,
  },
  selectNewNumbersBox2: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    marginTop: 10,
  },
  selectNewNumbersButton2: {
    height: 35,
    boxSizing: "border-box",
    padding: 0,
    padding: "0 20px",
    fontSize: 16,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
    background: "rgba(160, 160, 160, 1)",
    border: 0,
    borderRadius: 4,
    cursor: "pointer",
  },
  selectMessageModelBox2: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
    marginTop: 20,
  },
  selectMessageModelBoxTitle2: {
    fontSize: 18,
    color: "rgba(80, 80, 80, 1)",
    fontWeight: 600,
  },
  typeMessageBox2: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
    marginTop: 20,
  },
  typeMessageBoxTitle2: {
    fontSize: 18,
    color: "rgba(80, 80, 80, 1)",
    fontWeight: 600,
  },
  typeMessageBoxInput2: {
    width: "100%",
    height: 200,
    fontWeight: 500,
    fontSize: 16,
    padding: "10px 20px",
    boxSizing: "border-box",
    outline: "none",
    border: 0,
    boxShadow: "3px 3px 3px rgba(0,0,0,0.4)",
  },
  createButton2: {
    width: "100%",
    height: 40,
    border: 0,
    background: "rgba(100, 220, 0, 1)",
    color: "rgba(80, 80, 80, 1)",
    boxSizing: "border-box",
    fontSize: 18,
    marginTop: 10,
    borderRadius: 4,
    cursor: "pointer",
    transition: ".3s",
  },
  models: {
    width: "100%",
    display: "flex",
    gap: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  modelBox: {
    width: 150,
    height: 200,
    background: "rgba(230, 230, 230, 1)",
    borderRadius: 4,
  },
  paginationButton1: {
    width: 30,
    height: 30,
    borderRadius: 4,
    background: "rgba(180, 180, 180, 1)",
    color: "rgba(80, 80, 80, 1)",
    fontWeight: 800,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    border: 0,
    cursor: "pointer",
  },
  paginationView: {
    width: 40,
    height: 30,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    background: "white",
    fontSize: 16,
    color: "rgba(80, 80, 80, 1)",
  },
  paginationContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "8px",
    marginTop: "20px",
    marginBottom: "20px",
  },
  paginationButton: {
    padding: "8px 12px",
    border: "1px solid #e2e8f0",
    borderRadius: "6px",
    background: "white",
    cursor: "pointer",
    "&:hover": {
      background: "#f8fafc",
    },
    "&:disabled": {
      opacity: 0.5,
      cursor: "not-allowed",
    },
  },
  paginationButtonActive: {
    background: "#3b82f6",
    color: "white",
    borderColor: "#3b82f6",
    "&:hover": {
      background: "#2563eb",
    },
  },
  paginationEllipsis: {
    padding: "8px 12px",
  },
  loadingState: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "40px",
    color: "#64748b",
  },
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "40px",
    color: "#64748b",
  },
  emptyIcon: {
    fontSize: "40px",
    marginBottom: "16px",
  },
  searchButton: {
    width: "100%",
    height: 35,
    background: "#3b82f6",
    color: "white",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    "&:hover": {
      background: "#2563eb",
    },
    "&:disabled": {
      background: "#94a3b8",
      cursor: "not-allowed",
    },
  },
  //fim do modal de remarketing
};

export default style;
