const style = {
  containerGeneral: {
    width: "100vw",
    height: "100vh",
    position: "fixed",
    top: 0,
    left: 0,
    background: "rgba(0,0,0,0.6)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  modal: {
    borderRadius: 4,
    width: "80%",
    // height: "80%",
    padding: "30px 40px",
    boxSizing: "border-box",
    background: "rgba(210, 210, 210, 1)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    position: "relative",
  },
  deleteButton: {
    padding: "5px 20px",
    boxSizing: "border-box",
    background: "rgba(255, 100, 30, 1)",
    color: "rgba(80, 80, 80, 1)",
    fontWeight: 600,
    position: "absolute",
    cursor: "pointer",
    border: "1px solid rgba(80, 80, 80, 2)",
    borderRadius: 4,
    top: 15,
    right: 20,
    fontSize: 14
  },
  closeBtn: {
    position: "absolute",
    top: 15,
    left: 20,
    fontSize: 18,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
    cursor: "pointer",
  },
  title: {
    fontSize: 28,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
  },
  content: {
    display: "grid",
    width: "100%",
    gap: 10,
  },
  row: {
    display: "grid",
    gap: 10,
  },
  inputBox: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
  },
  inputBoxTitle: {
    fontSize: 18,
    color: "rgba(80, 80, 80, 1)",
    fontWeight: 600,
  },
  inputBoxInput: {
    width: "100%",
    height: 35,
    boxSizing: "border-box",
    padding: 0,
    paddingLeft: 20,
    outline: "none",
    fontSize: 16,
    fontWeight: 600,
    border: 0,
    boxShadow: "3px 3px 2px rgba(0,0,0,0.2)",
    color: "rgba(80, 80, 80, 1)",
    borderRadius: 4,
  },
  inputBoxTextarea: {
    width: "100%",
    height: 150,
    boxSizing: "border-box",
    padding: 0,
    paddingLeft: 20,
    outline: "none",
    padding: 10,
    color: "rgba(80, 80, 80, 1)",
    fontSize: 16,
    fontWeight: 600,
    border: 0,
    boxShadow: "3px 3px 2px rgba(0,0,0,0.2)",
    borderRadius: 4,
  },
  selectCategoriesButton: {
    width: "100%",
    height: 35,
    border: 0,
    cursor: "pointer",
    borderRadius: 4,
    fontSize: 16,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
    background: "rgba(0, 200, 220, 1)",
  },
  categoriesBoxTitle: {
    fontSize: 18,
    color: "rgba(80, 80, 80, 1)",
    fontWeight: 600,
  },
  categoriesBoxSubTitle: {
    fontSize: 12,
    color: "rgba(80, 80, 80, 0.6)",
    fontWeight: 500,
  },
  categoryBoxes: {
    width: "100%",
    maxHeight: 100,
    overflowY: "auto",
    boxSizing: "border-box",
    paddingTop: 10,
    paddingBottom: 10,
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "start",
    gap: 10,
  },
  category: {
    padding: "5px 20px",
    boxSizing: "border-box",
    background: "rgba(100, 255, 0, 0.6)",
    color: "rgba(80, 80, 80, 1)",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 600,
    borderRadius: 4,
    boxShadow: "3px 3px 4px rgba(0,0,0,0.2)",
  },
  saveButton: {
    width: "100%",
    height: 35,
    border: 0,
    borderRadius: 4,
    fontSize: 16,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
    background: "rgba(100, 255, 0, 1)",
  },
  underSavebuttonText: {
    fontSize: 12,
    fontWeight: 500,
    color: "rgba(80, 80, 80, 0.6)"
  }
};

export default style;
