const style = {
  modal: {
    width: "100%",
    height: "100%",
    background: "rgba(210, 210, 210, 1)",
    position: "relative",
    display: "flex",
    flexDirection: "column",
    boxSizing: "border-box",
    padding: "30px 40px",
    overflowY: "auto",
  },
  closeBtn: {
    position: "absolute",
    top: 30,
    left: 30,
    fontSize: 18,
    fontWeight: "600",
    color: "rgba(80, 80, 80, 1)",
    width: 60,
    height: 60,
    cursor: "pointer",
  },
  title: {
    fontSize: 28,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
  },
  modelContainer: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    marginTop: 40,
    maxHeight: 250,
    overflowY: "auto"
  },
  info: {
    width: "100%",
    marginTop: 20,
    display: "flex",
    flexDirection: "column",
  },
  firstRow: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "4fr 4fr",
    gap: 10,
  },
  firstRow1: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  firstRow1Box: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
  },
  firstRow1BoxTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
  },
  firstRow1BoxInput: {
    width: "100%",
    height: 35,
    outline: "none",
    border: 0,
    boxSizing: "border-box",
    padding: 0,
    paddingLeft: 20,
    borderRadius: 4,
    boxShadow: "4px 4px 5px rgba(0,0,0,0.1)",
    fontSize: 16,
    fontWeight: "600",
    color: "rgba(80, 80, 80, 1)",
  },
  firstRow1BoxTextarea: {
    width: "100%",
    height: 200,
    outline: "none",
    border: 0,
    boxSizing: "border-box",
    padding: 10,
    borderRadius: 4,
    boxShadow: "4px 4px 5px rgba(0,0,0,0.1)",
    fontSize: 16,
    fontWeight: "600",
    color: "rgba(80, 80, 80, 1)",
  },
  firstRow2: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  firstRow2Header: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "2fr 2fr",
    gap: 10,
  },
  firstRow2Box: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
  },
  firstRow2BoxTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
  },
  firstRow2BoxInput: {
    width: "100%",
    height: 35,
    outline: "none",
    border: 0,
    boxSizing: "border-box",
    padding: 0,
    paddingLeft: 20,
    borderRadius: 4,
    boxShadow: "4px 4px 5px rgba(0,0,0,0.1)",
    fontSize: 16,
    fontWeight: "600",
    color: "rgba(80, 80, 80, 1)",
  },
  firstRow2Body: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
  },
  historyTable: {
    width: "100%",
    height: 200,
    overflowY: "auto",
    borderRadius: 4,
    background: "white",
    boxShadow: "0 2px 10px rgba(0, 0, 0, 0.08)",
  },
  historyTableHeader: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    backgroundColor: "#4f46e5",
    color: "white",
    padding: "12px 16px",
    position: "sticky",
    top: 0,
    zIndex: 1,
  },
  historyTableHeaderCell: {
    fontSize: "14px",
    fontWeight: "600",
    textAlign: "center",
  },
  historyTableRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    padding: "12px 16px",
    borderBottom: "1px solid #e2e8f0",
    backgroundColor: "white",
    transition: "background-color 0.2s",
    "&:hover": {
      backgroundColor: "#f8fafc",
    },
    "&:last-child": {
      borderBottom: "none",
    },
  },
  historyTableCell: {
    fontSize: "14px",
    textAlign: "center",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "8px 0",
  },
  statusBadge: {
    padding: "4px 12px",
    borderRadius: "12px",
    fontSize: "12px",
    fontWeight: "500",
    display: "inline-block",
  },
  statusSuccess: {
    backgroundColor: "#ecfdf5",
    color: "#059669",
  },
  statusWarning: {
    backgroundColor: "#fef3c7",
    color: "#d97706",
  },
  statusError: {
    backgroundColor: "#fee2e2",
    color: "#dc2626",
  },
  sendNew: {
    width: "100%",
    height: 35,
    boxSizing: "border-box",
    padding: 0,fontSize: 16,
    fontWeight: 600,
    color: "rgba(80, 80, 80, 1)",
    cursor: "pointer",
    border: 0,
    borderRadius: 4,
    boxShadow: "4px 4px 4px rgba(0,0,0,0.2)",
    background: "rgba(100, 220, 0, 1)",
    marginTop: 10
  }
};

export default style;
